{{- if .Values.ingress.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.tlsSecret }}
  labels:
    app.kubernetes.io/name: {{ include "reporting-server.name" . }}
    helm.sh/chart: {{ include "reporting-server.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: kubernetes.io/tls
data:
    tls.crt: {{ .certificate | b64enc }}
    tls.key: {{ .key | b64enc }}
---
{{- end }}