version: 2

defaults: &defaults
  environment:
    - DOCKER_IMAGE: "tabit.azurecr.io/reportserver"
    - KUBECONFIG: .circleci/.azurek8s/kube_config

jobs:

  build:
    <<: *defaults
    docker:
      - image: circleci/node:6-browsers

    working_directory: ~/reporting-server

    steps:
      - checkout
      - run:
          command: |
            curl https://raw.githubusercontent.com/helm/helm/master/scripts/get > get_helm.sh
      - run:
          command: |
            chmod 700 get_helm.sh
      - run:
          command: |
            ./get_helm.sh
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/reporting-server
      - run:
          command: |
            docker build -t "$DOCKER_IMAGE":"${CIRCLE_BRANCH////_}-$(echo $CIRCLE_SHA1 | cut -c -7)" .
      - run:
          command: |
            docker login --username $DOCKER_USER --password $DOCKER_PASS tabit.azurecr.io
      - run:
          command: |
            docker push "$DOCKER_IMAGE":"${CIRCLE_BRANCH////_}-$(echo $CIRCLE_SHA1 | cut -c -7)"
      - run:
          command: |
            git clone https://github.com/inPact/helm-live.git /tmp/helm-live
      - run:
          command: |
            helm upgrade report-server ./tmp/helm-live/azure/dev/services/reporting-server --set image.tag="${CIRCLE_BRANCH////_}-$(echo $CIRCLE_SHA1 | cut -c -7)"
      #- run:
      #    command: |
      #      helm upgrade report-server ./helm/reporting-server --set image.tag="${CIRCLE_BRANCH////_}-$(echo $CIRCLE_SHA1 | cut -c -7)"


