{{- if not .Values.existingAirflowSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  labels:
    app.kubernetes.io/name: {{ include "reporting-server.name" . }}
    helm.sh/chart: {{ include "reporting-server.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    heritage: "{{ .Release.Service }}"
  annotations:
    "helm.sh/hook": pre-install,post-delete
    #"helm.sh/hook-delete-policy": "before-hook-creation"
type: Opaque
data:
  {{ .Values.secret.key }}: {{ .Values.secret.value }}
{{- end -}}
