apiVersion: v1
kind: Secret
metadata:
    name: {{ .Values.secret.name }}
    labels:
      app.kubernetes.io/name: {{ include "reporting-server.name" . }}
      helm.sh/chart: {{ include "reporting-server.chart" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/managed-by: {{ .Release.Service }}type: Opaque
    annotations:
      "helm.sh/hook": pre-install
type: Opaque
data: {{ .Values.secret.value | b64enc | quote }}
